[build]
  publish = "public"

# Proxy API calls to a dedicated backend (replace with your backend URL)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend.example.com/api/:splat"
  status = 200
  force = true

# Optional: allow admin routes too if they share /api prefix
[[redirects]]
  from = "/__debug/*"
  to = "https://your-backend.example.com/__debug/:splat"
  status = 200
  force = true