[build]
  publish = "public"
  command = "npm install && npm run build"

[functions]
  directory = "functions"

# Configuration pour les fonctions serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Redirection par défaut pour le SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200