[build]
  publish = "public"
  command = "npm install && npm run build"

[functions]
  directory = "functions"

# Configuration pour les fonctions serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Protection des pages admin et test
[[redirects]]
  from = "/admin.html"
  to = "/index.html"
  status = 302
  force = true
  conditions = {Role = ["!admin"]}

[[redirects]]
  from = "/test.html"
  to = "/index.html"
  status = 302
  force = true
  conditions = {Role = ["!teacher", "!admin"]}

# Redirection par défaut pour le SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200